name: flatpak
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  dbus: ^0.7.10
  ffi: ^2.1.2

dev_dependencies:
  ffigen: ^12.0.0
  lints: ^3.0.0
  test: ^1.24.0

ffigen:
  output: "lib/src/libflatpak.dart"
  headers:
    entry-points:
      - "/usr/include/flatpak/flatpak.h"

  functions:
    exclude:
      - "_g*" # Exclude all functions starting with _g.
      - "_G*"
      - "G*"
    include:
      - "flatpak.*" # Include all functions starting with flatpak.

  macros:
    exclude:
      - "_G*"
      - "G*"

  structs:
    exclude:
      - "_G*"
      - "G*"

  typedefs:
    exclude:
      - "_G*"
      - "G*"
