name: Generate libflatpak.dart bindings

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get

      - name: Generate bindings
        run: |
          chmod +x ./gen_bin.sh
          ./gen_bin.sh
        shell: bash
  
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Generate libflatpak.dart bindings.
